name = "osta-ranking-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RANKING_STORE"
id = "f8bffadeaef34fc19edd5aede1d6c6f4"

[triggers]
crons = ["0 9 * * 1"]
